/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
export const PAGES = {
	_ROOT: `/`,
	'0': `/0`,
	'1': `/1`,
	'1_auxilliary_living_room': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/auxilliary-living-room${appendSp({ statusView: params.statusView })}`;
	},
	'1_auxilliary_living_room_hotel': (params?: {
		statusView?: 'messages' | 'player' | 'giancarlo';
	}) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/auxilliary-living-room/hotel${appendSp({ statusView: params.statusView })}`;
	},
	'1_auxilliary_living_room_lizard_zone': (params?: {
		statusView?: 'messages' | 'player' | 'giancarlo';
	}) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/auxilliary-living-room/lizard-zone${appendSp({ statusView: params.statusView })}`;
	},
	'1_bathroom': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/bathroom${appendSp({ statusView: params.statusView })}`;
	},
	'1_doorway': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/doorway${appendSp({ statusView: params.statusView })}`;
	},
	'1_kitchen': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/kitchen${appendSp({ statusView: params.statusView })}`;
	},
	'1_laboratory': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/laboratory${appendSp({ statusView: params.statusView })}`;
	},
	'1_living_room': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/living-room${appendSp({ statusView: params.statusView })}`;
	},
	'1_living_room_poäng': (params?: { statusView?: 'messages' | 'player' | 'giancarlo' }) => {
		params = params ?? {};
		params.statusView = params.statusView ?? 'messages';
		return `/1/living-room/poäng${appendSp({ statusView: params.statusView })}`;
	},
	'2': `/2`,
	reset: `/reset`
};

/**
 * SERVERS
 */
export const SERVERS = {};

/**
 * ACTIONS
 */
export const ACTIONS = {
	grabCat_1: `/1?/grabCat`,
	releaseCat_1: `/1?/releaseCat`,
	brushCatTeeth_1: `/1?/brushCatTeeth`,
	regardLizard_1_auxilliary_living_room: `/1/auxilliary-living-room?/regardLizard`,
	pickUp_1_auxilliary_living_room_hotel: `/1/auxilliary-living-room/hotel?/pickUp`,
	talkToLizard_1_auxilliary_living_room_lizard_zone: `/1/auxilliary-living-room/lizard-zone?/talkToLizard`,
	giveLizardLettuce_1_auxilliary_living_room_lizard_zone: `/1/auxilliary-living-room/lizard-zone?/giveLizardLettuce`,
	ignoreLizard_1_auxilliary_living_room_lizard_zone: `/1/auxilliary-living-room/lizard-zone?/ignoreLizard`,
	observe_1_bathroom: `/1/bathroom?/observe`,
	regardPantry_1_bathroom: `/1/bathroom?/regardPantry`,
	takeZyrtec_1_bathroom: `/1/bathroom?/takeZyrtec`,
	regardCabinet_1_bathroom: `/1/bathroom?/regardCabinet`,
	grabToothbrush_1_bathroom: `/1/bathroom?/grabToothbrush`,
	pickUpFish_1_bathroom: `/1/bathroom?/pickUpFish`,
	takeOffShoes_1_doorway: `/1/doorway?/takeOffShoes`,
	putOnShoes_1_doorway: `/1/doorway?/putOnShoes`,
	open_1_doorway: `/1/doorway?/open`,
	close_1_doorway: `/1/doorway?/close`,
	enter_1_doorway: `/1/doorway?/enter`,
	leave_1_doorway: `/1/doorway?/leave`,
	greet_1_doorway: `/1/doorway?/greet`,
	regardDeadbolt_1_doorway: `/1/doorway?/regardDeadbolt`,
	regardKnobLock_1_doorway: `/1/doorway?/regardKnobLock`,
	tryDeadboltTeethUp_1_doorway: `/1/doorway?/tryDeadboltTeethUp`,
	tryDeadboltTeethDown_1_doorway: `/1/doorway?/tryDeadboltTeethDown`,
	tryKnobLockTeethUp_1_doorway: `/1/doorway?/tryKnobLockTeethUp`,
	tryKnobLockTeethDown_1_doorway: `/1/doorway?/tryKnobLockTeethDown`,
	observe_1_kitchen: `/1/kitchen?/observe`,
	regardSink_1_kitchen: `/1/kitchen?/regardSink`,
	regardRefridgerator_1_kitchen: `/1/kitchen?/regardRefridgerator`,
	openRefridgerator_1_kitchen: `/1/kitchen?/openRefridgerator`,
	closeRefridgerator_1_kitchen: `/1/kitchen?/closeRefridgerator`,
	takeLettuce_1_kitchen: `/1/kitchen?/takeLettuce`,
	drinkBeer_1_kitchen: `/1/kitchen?/drinkBeer`,
	turnOnFaucet_1_kitchen: `/1/kitchen?/turnOnFaucet`,
	turnOffFaucet_1_kitchen: `/1/kitchen?/turnOffFaucet`,
	washLettuce_1_kitchen: `/1/kitchen?/washLettuce`,
	chopLettuce_1_kitchen: `/1/kitchen?/chopLettuce`,
	pickUpBall_1_kitchen: `/1/kitchen?/pickUpBall`,
	observe_1_living_room: `/1/living-room?/observe`,
	takeOffShoes_1_living_room: `/1/living-room?/takeOffShoes`,
	putOnShoes_1_living_room: `/1/living-room?/putOnShoes`,
	regardLizard_1_living_room: `/1/living-room?/regardLizard`,
	regardChair_1_living_room: `/1/living-room?/regardChair`,
	inspectRug_1_living_room: `/1/living-room?/inspectRug`,
	sit_1_living_room_poäng: `/1/living-room/poäng?/sit`,
	stand_1_living_room_poäng: `/1/living-room/poäng?/stand`,
	callForCat_1_living_room_poäng: `/1/living-room/poäng?/callForCat`,
	regardItch_1_living_room_poäng: `/1/living-room/poäng?/regardItch`,
	strikeBird_1_living_room_poäng: `/1/living-room/poäng?/strikeBird`,
	throwBall_1_living_room_poäng: `/1/living-room/poäng?/throwBall`,
	throwFish_1_living_room_poäng: `/1/living-room/poäng?/throwFish`
};

/**
 * LINKS
 */
export const LINKS = {};

type ParamValue = string | number | undefined;

/**
 * Append search params to a string
 */
export const appendSp = (
	sp?: Record<string, ParamValue | ParamValue[]>,
	prefix: '?' | '&' = '?'
) => {
	if (sp === undefined) return '';

	const params = new URLSearchParams();
	const append = (n: string, v: ParamValue) => {
		if (v !== undefined) {
			params.append(n, String(v));
		}
	};

	for (const [name, val] of Object.entries(sp)) {
		if (Array.isArray(val)) {
			for (const v of val) {
				append(name, v);
			}
		} else {
			append(name, val);
		}
	}

	const formatted = params.toString();
	if (formatted) {
		return `${prefix}${formatted}`;
	}
	return '';
};

/**
 * get the current search params
 *
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */
export const currentSp = () => {
	const params = new URLSearchParams(window.location.search);
	const record: Record<string, string> = {};
	for (const [key, value] of params.entries()) {
		record[key] = value;
	}
	return record;
};

/**
 * Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
 *
 * Full example:
 * ```ts
 * import type { KIT_ROUTES } from '$lib/ROUTES'
 * import { kitRoutes } from 'vite-plugin-kit-routes'
 *
 * kitRoutes<KIT_ROUTES>({
 *  PAGES: {
 *    // here, key of object will be typed!
 *  }
 * })
 * ```
 */
export type KIT_ROUTES = {
	PAGES: {
		_ROOT: never;
		'0': never;
		'1': never;
		'1_auxilliary_living_room': never;
		'1_auxilliary_living_room_hotel': never;
		'1_auxilliary_living_room_lizard_zone': never;
		'1_bathroom': never;
		'1_doorway': never;
		'1_kitchen': never;
		'1_laboratory': never;
		'1_living_room': never;
		'1_living_room_poäng': never;
		'2': never;
		reset: never;
	};
	SERVERS: Record<string, never>;
	ACTIONS: {
		grabCat_1: never;
		releaseCat_1: never;
		brushCatTeeth_1: never;
		regardLizard_1_auxilliary_living_room: never;
		pickUp_1_auxilliary_living_room_hotel: never;
		talkToLizard_1_auxilliary_living_room_lizard_zone: never;
		giveLizardLettuce_1_auxilliary_living_room_lizard_zone: never;
		ignoreLizard_1_auxilliary_living_room_lizard_zone: never;
		observe_1_bathroom: never;
		regardPantry_1_bathroom: never;
		takeZyrtec_1_bathroom: never;
		regardCabinet_1_bathroom: never;
		grabToothbrush_1_bathroom: never;
		pickUpFish_1_bathroom: never;
		takeOffShoes_1_doorway: never;
		putOnShoes_1_doorway: never;
		open_1_doorway: never;
		close_1_doorway: never;
		enter_1_doorway: never;
		leave_1_doorway: never;
		greet_1_doorway: never;
		regardDeadbolt_1_doorway: never;
		regardKnobLock_1_doorway: never;
		tryDeadboltTeethUp_1_doorway: never;
		tryDeadboltTeethDown_1_doorway: never;
		tryKnobLockTeethUp_1_doorway: never;
		tryKnobLockTeethDown_1_doorway: never;
		observe_1_kitchen: never;
		regardSink_1_kitchen: never;
		regardRefridgerator_1_kitchen: never;
		openRefridgerator_1_kitchen: never;
		closeRefridgerator_1_kitchen: never;
		takeLettuce_1_kitchen: never;
		drinkBeer_1_kitchen: never;
		turnOnFaucet_1_kitchen: never;
		turnOffFaucet_1_kitchen: never;
		washLettuce_1_kitchen: never;
		chopLettuce_1_kitchen: never;
		pickUpBall_1_kitchen: never;
		observe_1_living_room: never;
		takeOffShoes_1_living_room: never;
		putOnShoes_1_living_room: never;
		regardLizard_1_living_room: never;
		regardChair_1_living_room: never;
		inspectRug_1_living_room: never;
		sit_1_living_room_poäng: never;
		stand_1_living_room_poäng: never;
		callForCat_1_living_room_poäng: never;
		regardItch_1_living_room_poäng: never;
		strikeBird_1_living_room_poäng: never;
		throwBall_1_living_room_poäng: never;
		throwFish_1_living_room_poäng: never;
	};
	LINKS: Record<string, never>;
	Params: { statusView: never };
};
